export const CLIENTE_REQUEST = "CLIENTE_REQUEST";
export const CLIENTE_SUCCESS = "CLIENTE_SUCCESS";
export const CLIENTE_FALURE = "CLIENTE_FALURE";

export const CLIENTE_EDITAR_REQUEST = "CLIENTE_EDITAR_REQUEST";
export const CLIENTE_EDITAR_SUCCESS = "CLIENTE_EDITAR_SUCCESS";
export const CLIENTE_EDITAR_FALURE = "CLIENTE_EDITAR_FALURE";

export const CLIENTE_BUSCAR_REQUEST = "CLIENTE_BUSCAR_REQUEST";
export const CLIENTE_BUSCAR_SUCCESS = "CLIENTE_BUSCAR_SUCCESS";
export const CLIENTE_BUSCAR_FALURE = "CLIENTE_BUSCAR_FALURE";

export const CLIENTE_DELETAR_REQUEST = "CLIENTE_DELETAR_REQUEST";
export const CLIENTE_DELETAR_SUCCESS = "CLIENTE_DELETAR_SUCCESS";
export const CLIENTE_DELETAR_FALURE = "CLIENTE_DELETAR_FALURE";

export const ROUTE_BUSCAR_REQUEST = "ROUTE_BUSCAR_REQUEST";
export const ROUTE_BUSCAR_SUCCESS = "ROUTE_BUSCAR_SUCCESS";
export const ROUTE_BUSCAR_FALURE = "ROUTE_BUSCAR_FALURE";
